### ISSUE TITLE
Compatibility with ember-rapid-forms

### ISSUE THREAD

**Issue by toovy** [adopted-ember-addons/ember-cp-validations#382]
Hi,

as ember-validations served as basis for ember-rapid-forms and ember-validations references this project I think it is a good idea to make both addons compatible out of the box.

As ember-rapid-forms uses the errors object on a model a simple drop in of ember-cp-validations does not work. A solution by @GCorbel is the mixin listed here:

https://github.com/piceaTech/ember-rapid-forms/issues/139#issuecomment-257267011

The following issues might also be related:

https://github.com/offirgolan/ember-cp-validations/issues/157
https://github.com/offirgolan/ember-cp-validations/issues/175

Personally I feel that the compatibility code (e.g. the mixin from @GCorbel) should reside in ember-cp-validations. As I'm not really into the code of both projects I cannot really say if a mixin would be a good solution or if that could maybe implemented as validator or global setting.

Thanks for looking into this, BR, toovy

**Comment by GCorbel** [comment]
@offirgolan any update on this issue ?

**Comment by offirgolan** [comment]
@toovy @GCorbel sorry for the detail, Im out of the country so my response times may be a bit slow. I don't really have the time to look too much into this but from my earlier attempt to get this sort of feature working, I ran into many obstacles when dealing with different versions of ember-data, hence why I dropped it. 

Honestly speaking, I don't really think that syncing the two error collections is a good idea. I believe that a form library should not be dependent on the validations that a user might want to use because it just creates a scalability issue. Instead, there should be some sort of public API that a 3rd party addon can be written to add support for a given validation library. There are a ton of examples like that out there in the addon ecosystem today.

**Comment by GCorbel** [comment]
@offirgolan that's a good idea. I also think this mixin should not be included in the form library. This is not really related to forms but to validations. This is why I thank it was more appropriate to include it in ember-cp-validations. I will create "ember-cp-validations-ds-errors"  if you wish.

**Comment by offirgolan** [comment]
@GCorbel I think the best and fastest solution as of right now would be to create _ember-cp-validations-ds-errors_. I'm gonna be traveling the next few weeks so I wont have too much time to look into this unfortunately. If you need any help in developing the addon, feel free to shoot me a message on slack. A good starting point would be to check out ember-bootstrap-cp-validations 😄. 

Once I'm back maybe we can work together to get this into the library!

**Comment by rwwagner90** [comment]
Closing some old issues as wontfix for now. If this issue is still relevant, please feel free to open a new one!
