### ISSUE TITLE
Best approach, validate nested attr

### ISSUE THREAD

**Issue by rossjha** [adopted-ember-addons/ember-cp-validations#585]
I have dynamic nested attrs i need to validate.  A custom validator would be ideal.  I want to retrieve the required attrs from a service and check that each nested attr has a value.

How would i manually validate when a nested attr is updated?

`title: {
  en: '',
  fr: '',
  de: ''
}`

**Comment by viniciussbs** [comment]
@rossjha I don't know if it's the same case, but the API I'm using has some fields like `post.titles` that returns an object like the one you mentioned: `{ pt: 'Olá, Mundo!', en: 'Hello, World!' }`.

So, when I'm creating a `post`, I have an `<input>` for each `title` translation. The tricky part is that I don't have the languages list beforehand. I have to look the `post.titles` property and, for each key, create the validations dynamically. That's how I've solved it:

```js
// app/components/post-form.js

import Component from '@ember/component';
import { validator } from 'ember-cp-validations';
import buildDynamicValidations from 'my-app/utils/build-dynamic-validations';

const Validations = {
  'post.publishedAt': [
    validator('presence', {
      presence: true
    })
  ],
  'post.titles.@eachKey': [
    validator('presence', {
      presence: true
    })
  ],
  'post.bodies.@eachKey': [
    validator('presence', {
      presence: true
    })
  ]
};

export default Component.extend({
  init() {
    this._super(...arguments);
    this.reopen(buildDynamicValidations(this, Validations));
  },

  // ...
});
```

The `'post.titles.@eachKey'` and `'.post.bodies.@eachKey'` notation means that the validations will not be applied to `post.titles` nor `post.bodies`, but to each of their keys instead. Which means `post.titles.pt`, `post.titles.en`, `post.bodies.pt` and `post.bodies.pt`.

This notation is something that I came up with because I have this logic spread throughout my hole app, and this way I can reduce the repeated code.

```js
// app/utils/build-dynamic-validations.js

function buildDynamicValidations(scope, validationsMap) {
  let validations = {};
  let propertiesToValidate = Object.keys(validationsMap);

  propertiesToValidate.forEach((fullPropertyPath) => {
    let propertyValidations = validationsMap[fullPropertyPath];
    let shouldApplyValidationsNestedProperties = fullPropertyPath.endsWith('.@eachKey');

    if (shouldApplyValidationsNestedProperties) {
      let [propertyPath] = fullPropertyPath.split('.@eachKey');
      let nestedPropertiesToValidate = Object.keys(get(scope, propertyPath));

      nestedPropertiesToValidate.forEach((key) => {
        validations[`${propertyPath}.${key}`] = propertyValidations;
      });
    } else {
      validations[fullPropertyPath] = propertyValidations;
    }
  });

  return buildValidations(validations);
}
```

I'm planning to detect every string that end of variations of `/@each.+$/`, so I can have more meaningful descriptions:

```js
const Validations = {
  'post.titles.@eachTranslation': [
    validator('presence', {
      presence: true
    })
  ],

  'someListsOrganizedBySomeIdentifier.@eachList': [
    validator('length', {
      min: 1
    })
  ],
};
```

@offirgolan Do you think this notation of `.@eachKey` is something that other people could benefit from? 🤔 I did it inspired by the computed property notation for array properties.

**Comment by fsmanuel** [comment]
@rossjha I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
